# This Docker Compose file is used to create PostgreSQL and pgAdmin containers.
# To use this configuration, navigate to the directory containing this file and execute:
# docker-compose up -d

version: "3.8"

services:
  db:
    container_name: postgres_container
    image: postgres:16.0
    restart: always
    env_file:
      - database.env
    ports:
      - "5432:5432"
    volumes:
      - D:\\database\\postgresql\\postgres_data:/var/lib/postgresql/data
    networks:
      docker-compose-postgresal-pgadmin_mynetwork:
        ipv4_address: 172.18.0.10  # Choose an available IP address within the subnet

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:7.7
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    volumes:
      - D:\\database\\postgresql\\pgadmin_data:/var/lib/pgadmin
    networks:
      docker-compose-postgresal-pgadmin_mynetwork:
        ipv4_address: 172.18.0.11  # Choose an available IP address within the subnet

  redis:
    image: redis:latest
    container_name: redis_container
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - D:\\database\\redis_data:/data
    networks:
      docker-compose-postgresal-pgadmin_mynetwork:
        ipv4_address: 172.18.0.12  # Choose an available IP address within the subnet

networks:
  docker-compose-postgresal-pgadmin_mynetwork:
    external: true
    name: docker-compose-postgresal-pgadmin_mynetwork
